### ISSUE TITLE
Need Advice for laravel integration

### ISSUE THREAD

**Issue by deep80** [nasirouwagana/vuebase#1]
hi,

saw the theme and the design looks very professional. is there a way to integrate this theme with laravel since the framework (php) does have support for vue.js.

**Comment by nasirouwagana** [comment]
@deep80 Happy you love Vuebase. 
You can easily integrate Vuebase with Laravel. You need to copy the whole content of this repository **src** directory inside a Laravel directory **resources/assets**. Then, add project dependencies in **package.json**. And finally, configure **webpack.mix.js** to compile your JavaScript and Stylus Files.

**Comment by deep80** [comment]
Hi, I followed everything as you said and i am getting errors while compiling. The error codes from the terminal are as follows:

ERROR in ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-73652532","scoped":true,"hasInlineConfig":true}!./node_modules/stylus-loader!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./resources/assets/js/components/layouts/VuebaseLayout.vue
Module build failed: Error: D:\Important\practise\laravel\resources\assets\js\components\layouts\VuebaseLayout.vue:328:9
   324|     }
   325| </script>
   326|
   327| <style scoped lang="stylus">
   328|     @import '../../node_modules/vuetify/src/stylus/settings/_variables.styl'
----------------^
   329|
   330|     .bottom-menu {
   331|         position: absolute;

failed to locate @import file ../../node_modules/vuetify/src/stylus/settings/_variables.styl

    at CachedPathEvaluator.visitImport (D:\Important\practise\laravel\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (D:\Important\practise\laravel\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (D:\Important\practise\laravel\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (D:\Important\practise\laravel\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (D:\Important\practise\laravel\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (D:\Important\practise\laravel\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (D:\Important\practise\laravel\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (D:\Important\practise\laravel\node_modules\stylus\lib\renderer.js:86:26)
    at D:\Important\practise\laravel\node_modules\stylus-loader\index.js:167:12
    at tryCatchReject (D:\Important\practise\laravel\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (D:\Important\practise\laravel\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (D:\Important\practise\laravel\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (D:\Important\practise\laravel\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (D:\Important\practise\laravel\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (D:\Important\practise\laravel\node_modules\when\lib\Scheduler.js:27:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-73652532","scoped":true,"hasInlineConfig":true}!./node_modules/stylus-loader!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./resources/assets/js/components/layouts/VuebaseLayout.vue 4:14-370
 @ ./resources/assets/js/components/layouts/VuebaseLayout.vue
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/App.vue
 @ ./resources/assets/js/components/App.vue
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js

please advice ??

**Comment by nasirouwagana** [comment]
@deep80 I have just created a project for Vuebase Laravel integration : https://github.com/nasirouwagana/laravel-vuebase.
Please read README.md for installation. I hope you enjoy it.
